### ISSUE TITLE
Remove column or row name

### ISSUE THREAD

**Issue by zhangzmr** [ben-laufer/scDotPlot#1]
Hi , Thanks for this nice package! Is it possible to remove column names or row names? Cell type names is long, only needed in the legend but not in column at bottom. I am using a SingleCellExperiment object. Found that the ggplot language is not work here. 

Example code:
`scDotPlot(sce, features = intergene, group = "Celltype", groupAnno = "Celltype", 
          scale = TRUE, fontSize = 14, clusterColumns = FALSE, 
          dotColors = c("#1B3B70", "#F8F4F2", "#700C22"))`

Thank you!

**Comment by ben-laufer** [comment]
Hi @zhanzmr, here's an example of how to edit the dot plot:

```
library(scDotPlot)

data("pbmc_small", package = "SeuratObject")

p1 <- pbmc_small |>
    scDotPlot(features = Seurat::VariableFeatures(pbmc_small),
              group = "RNA_snn_res.1")

p1$plotlist[[1]] <- p1$plotlist[[1]] +
    ggplot2::theme(axis.text.x = ggplot2::element_blank())

p1
```

**Comment by zhangzmr** [comment]
Got it. Thanks so much!
